### ISSUE TITLE
license details

### ISSUE THREAD

**Issue by karan** [cosmocode/icke-template#3]
Please add a proper open source license to make this code usable by others. I recommend MIT License.

**Comment by splitbrain** [comment]
All DokuWiki templates are GPL-2 licensed as is this one. But yeah we'll add proper license info

**Comment by splitbrain** [comment]
@micgro42 commits bitte in unser gitlab/master, das wird automatisch hierher gesynct.

**Comment by micgro42** [comment]
Done in commit c9a7367e7728177fdfb8fe2f5919c005e39eb63a
